services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: collect_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ddd_laravel
      - DB_USERNAME=ghostg
      - DB_PASSWORD=ghostG2025@
    user: "${UID:-1000}:${GID:-1000}"

  mysql:
    image: mysql:8.0
    container_name: collect_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddd_laravel
      MYSQL_USER: ghostg
      MYSQL_PASSWORD: ghostG2025@
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    container_name: collect_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
    driver: local
  dbdata:
